name: Sandbox
on:
  push
jobs:
    test-sandbox:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                  repository: near/nearcore
            
            - uses: actions/cache@v2
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: 'Make Sandbox'
              working-directory: ./
              if: steps.cache.outputs.cache-hit != 'true'
              run: make sandbox

            - name: 'Building near'
              working-directory: ./
              run: |
                  rm -rf /tmp/near-sandbox
                  target/debug/near-sandbox --home /tmp/near-sandbox init
                  target/debug/near-sandbox --home /tmp/near-sandbox run &
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '15'
            - name: 'Building contracts'
              working-directory: ./
              run: |
                  ls
            - name: 'Testing contracts'
              working-directory: ./
              run: |
                  ls

